{
    "name": "IT Asset Management",
    "version": "13.0.1.0.0",
    "author": "Md Rockibul Alam Babu",
    "category": "IT Asset Management",
    "website": "",
    "depends": ['hr','product'],
    "license": "AGPL-3",
    "summary": "IT Asset Management to Manage IT assets for any company or offices",
    "data": [
        "security/it_asset_security.xml",
        "security/ir.model.access.csv",
        "report/report_view.xml",
        "report/report_assets_policy.xml",
        "report/report_assets_receive.xml",
        "report/report_assets_return.xml",
        "views/it_asset_view.xml",
        "views/product_product.xml",
        "views/actions.xml",
        "views/menus.xml",
    ],
    "images": ["static/description/icon.png"],
    "application": True,
}
